CREATE TABLE IF NOT EXISTS riders (
    id UUID PRIMARY KEY,
    user_id UUID REFERENCES users(id),
    vehicle_type VARCHAR(255),
    license_number VARCHAR(255),
    is_active BOOLEAN,
    profile_img VARCHAR,
    opening_time TIMESTAMPTZ,
    closing_time TIMESTAMPTZ,
    current_latitude DECIMAL(10,8),
    current_longitude DECIMAL(11,8),
    rating INTEGER,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ
);
